[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/formulaire-recrutement"
  to = "/formulaire-recrutement.html"
  status = 200

[[redirects]]
  from = "/dashboard-founder"
  to = "/dashboard-founder.html"
  status = 200

[[redirects]]
  from = "/dashboard-commercial"
  to = "/dashboard-commercial.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
